general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/xalk/.config/hypr/walpepers/back.jpg
    color = rgba(25, 20, 20, 0.5)
    blur_passes = 3 # Размытие фона для акцента на часах
}

# ЧАСЫ
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 120
    font_family = JetBrainsMono Nerd Font # Убедитесь, что шрифт установлен
    position = 0, 150
    halign = center
    valign = center
}

# ПОЛЕ ВВОДА ПАРОЛЯ
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    dots_size = 0.23
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(62, 143, 176)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(62, 143, 176) 
    fade_on_empty = false 
    ignore_combined_name = true
    placeholder_text = Password...
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}
