#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,ru
        kb_variant =
        kb_model =
        kb_options =grp:alt_shift_toggle,ctrl:nocaps
        kb_rules =


# 1 - фокус следует за мышью, 0 - только по клику, 2 - полная изоляция
        follow_mouse = 1
# Важно: новое окно забирает фокус, но не перемещает курсор
        mouse_refocus = 0
        sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

        touchpad {
            natural_scroll = false
        }
}
