# BEGIN_KITTY_THEME
# Aquarium Dark
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# END_KITTY_FONTS

# KAYBINDS
map alt+h send_text all ~/

# Убирает внутренние отступы (padding)
window_padding_width 0

# Убирает отступы по бокам, если размер окна не кратен размеру символа
placement_strategy center

# (Опционально) Если хочешь, чтобы текст был совсем вплотную к рамке:
single_window_margin_width 0
